//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CounselorApp.Administrator {
    using System;
    using CodeGenerator;
    using System.Collections.Generic;
    using System.Windows.Forms;
    using System.IO;
    using System.Linq;
    using System.Windows;
    using System.CodeDom;
    
    
    public partial class AddNewAdvice : Window {
        
        public AddNewAdvice() {
            InitializeComponent();
        }
        
        private void ClickUploadVulnerableWebButton(object sender, RoutedEventArgs e) {
            try {
                var dialog = new FolderBrowserDialog();
                dialog.ShowDialog();
                VulnerableWebTextBox.Text = dialog.SelectedPath;
                string className = "AddNewAdvice";
                string nameSpace = "CounselorApp.Administrator";
                var cds = new WPFAddNewAdviceGeneratorCode();
                CodeCompileUnit newClassCode = cds.GenerateCSharpCode(className, nameSpace);
                cds.GenerateCode(newClassCode, className);
                cds.SwitchClass(className, Directory.GetCurrentDirectory());
                Logger.Instance.Info("ClickUploadVulnerableWebButton()");
            }
            catch (Exception ex) {
                Logger.Instance.Error("Error while trying to Click Upload Vulnerable Web Button  ", ex);
            }
        }
        
        private void ClickUploadProtectedWebButton(object sender, RoutedEventArgs e) {
            try {
                var dialog = new FolderBrowserDialog();
                dialog.ShowDialog();
                ProtectedWebTextBox.Text = dialog.SelectedPath;
                Logger.Instance.Info("ClickUploadProtectedWebButton()");
            }
            catch (Exception ex) {
                Logger.Instance.Error("Error while trying to Click Upload Protected Web Button ", ex);
            }
        }
        
        private void UploadButton(object sender, RoutedEventArgs e) {
            try {
                Logger.Instance.Info("UploadButton()");
            }
            catch (Exception ex) {
                Logger.Instance.Error("Error while trying to Click Upload Protected Web Button  ", ex);
            }
        }
        
        private void ClickUploadButtonProtected(object sender, RoutedEventArgs e) {
            try {
                string sourceFile = ProtectedWebTextBox.Text;
                string destinationFile = ProtectedWebTextBox.Text;
                System.Collections.Generic.List<string> listPath = destinationFile.Split('\\').ToList();
                var nameDirectory = listPath[listPath.Count - 1];
                Directory.Move(ProtectedWebTextBox.Text, Directory.GetCurrentDirectory() +'\\'+ nameDirectory);
                UploadProtectedWebButton.IsEnabled = false;
                UploadButtonProtected.IsEnabled = false;
                ProtectedWebTextBox.IsEnabled = false;
                Logger.Instance.Info("ClickUploadButtonProtected()");
            }
            catch (Exception ex) {
                Logger.Instance.Error("Error while trying to Click Upload Button Protected  ", ex);
            }
        }
        
        private void ClickUploadButtonVulnerbale(object sender, RoutedEventArgs e) {
            try {
                string destinationFile = VulnerableWebTextBox.Text;
                System.Collections.Generic.List<string> listPath = destinationFile.Split('\\').ToList();
                var nameDirectory = listPath[listPath.Count - 1];
                Directory.Move(VulnerableWebTextBox.Text, Directory.GetCurrentDirectory() + '\\' + nameDirectory);
                UploadVulnerableWebButton.IsEnabled = false;
                UploadButtonVulnerbale.IsEnabled = false;
                VulnerableWebTextBox.IsEnabled = false;
            }
            catch (Exception ex) {
                Logger.Instance.Error("Error while trying to Click Upload Button Vulnerbale  ", ex);
            }
        }
    }
}
