//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGenerator {
    using System.Diagnostics;
    using CodeGenerator;
    using System.CodeDom;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class DoS {
        
        private System.Diagnostics.Process p;
        
        public DoS() {
            p.StartInfo.WorkingDirectory = "C:\\Users\\Liran\\Desktop\\WebTest";
            p.StartInfo.WindowStyle  = ProcessWindowStyle.Hidden;
            p.StartInfo.FileName = "cmd.exe";
            p.StartInfo.Arguments = "/c node app.js";
        }
        
        public static void Main() {
        }
        
        public void StartServer() {
            p.Start();
        }
        
        public void ShutDown() {
            p.Kill();
            p.Dispose();
        }
        
        public void OpenBrowserd() {
            Process.Start("http://:3000");
        }
    }
    
    public class DoS {
        
        private System.Diagnostics.Process p;
        
        public DoS() {
            p.StartInfo.WorkingDirectory = "C:\\Users\\Liran\\Desktop\\WebTest";
            p.StartInfo.WindowStyle  = ProcessWindowStyle.Hidden;
            p.StartInfo.FileName = "cmd.exe";
            p.StartInfo.Arguments = "/c node app.js";
        }
        
        public static void Main() {
        }
        
        public void StartServer() {
            p.Start();
        }
        
        public void ShutDown() {
            p.Kill();
            p.Dispose();
        }
        
        public void OpenBrowserd() {
            Process.Start("http://:3000");
        }
    }
}
namespace CodeGenerator {
    using System.Diagnostics;
    using CodeGenerator;
    using System.CodeDom;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class DoS {
        
        private System.Diagnostics.Process p;
        
        public DoS() {
            p.StartInfo.WorkingDirectory = "C:\\Users\\Liran\\Desktop\\WebTest";
            p.StartInfo.WindowStyle  = ProcessWindowStyle.Hidden;
            p.StartInfo.FileName = "cmd.exe";
            p.StartInfo.Arguments = "/c node app.js";
        }
        
        public static void Main() {
        }
        
        public void StartServer() {
            p.Start();
        }
        
        public void ShutDown() {
            p.Kill();
            p.Dispose();
        }
        
        public void OpenBrowserd() {
            Process.Start("http://:3000");
        }
    }
    
    public class DoS {
        
        private System.Diagnostics.Process p;
        
        public DoS() {
            p.StartInfo.WorkingDirectory = "C:\\Users\\Liran\\Desktop\\WebTest";
            p.StartInfo.WindowStyle  = ProcessWindowStyle.Hidden;
            p.StartInfo.FileName = "cmd.exe";
            p.StartInfo.Arguments = "/c node app.js";
        }
        
        public static void Main() {
        }
        
        public void StartServer() {
            p.Start();
        }
        
        public void ShutDown() {
            p.Kill();
            p.Dispose();
        }
        
        public void OpenBrowserd() {
            Process.Start("http://:3000");
        }
    }
}
